
SENATOR, ACADEMIC_VP, EXTERNAL_VP, EXECUTIVE_VP, STUDENT_ADVOCATE, PRESIDENT = range(1, 7)

RUNNING, WIN, LOSE = range(1,3)

POSITIONS = [SENATOR, ACADEMIC_VP, EXTERNAL_VP, EXECUTIVE_VP, STUDENT_ADVOCATE, PRESIDENT]

NUM_SENATORS = 20